### ISSUE TITLE
23/05/25

### ISSUE THREAD

**Issue by sjbae1999** [hyukji/multi-device-io#1]
1. 평가
a. 프로세스와 쓰레드

간의 메모리 사용량/핑 비교

b. tcp와 udp

둘 사이의 핑과 유실 정도(샘플 10000개 정도)
: 핑 차이 얼마 안나면 무조건 tcp가 맞다.

--> 유실 발생하지 않을 경우 : 우리의 경우는 udp 방식이 더 알맞다.
--> 유실 발생할 경우 : ping과 유실 정도의 trade off를 고려, 우리가 목표하는 작업(게임)에 어떤 통신 방식이 알맞은 지 결정.

2. 보여주기
테트리스 게임

3. 개선점
멀티 os

**Comment by hyukji** [comment]
1. ping테스트
2. 하드웨어 제작
3. struct 정확히 어떻게 입력하는가
